# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Volta
        uses: volta-cli/action@v1
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm -r lint
      - name: Tests
        run: pnpm -r test:ember

  test-try:
    name: Ember Try (${{ matrix.scenario }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: ember-lts-3.24
            allow-failure: false
          - scenario: ember-lts-3.28
            allow-failure: false
          - scenario: ember-release
            allow-failure: false
          - scenario: ember-beta
            allow-failure: false
          - scenario: ember-canary
            allow-failure: false
          - scenario: embroider-safe
            allow-failure: false
          - scenario: embroider-optimized
            allow-failure: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Volta
        uses: volta-cli/action@v1
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6
      - name: Install Dependencies
        run: pnpm install
      - name: Try Scenario
        run: pnpm test:try ${{ matrix.scenario }} --filter test-app
        continue-on-error: ${{ matrix.allow-failure }}
