# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lerna Bootstrap
        run: yarn run lerna bootstrap
      - name: Lint
        run: yarn workspaces run lint
      - name: Tests
        run: yarn workspaces run test:ember

  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lerna Bootstrap
        run: yarn run lerna bootstrap
      - name: Lint
        run: yarn workspaces run lint
      - name: Browser Tests
        run: yarn workspaces run test:ember

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lerna Bootstrap
        run: yarn run lerna bootstrap
      - name: Browser Tests
        run: yarn workspaces run test:ember

  test-try:
    name: Ember Try (${{ matrix.scenario }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: ember-lts-3.24
            allow-failure: false
          - scenario: ember-release
            allow-failure: false
          - scenario: ember-beta
            allow-failure: true
          - scenario: ember-canary
            allow-failure: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lerna Bootstrap
        run: yarn run lerna bootstrap
      - name: Try Scenario
        run: yarn workspace ember-statecharts run ember try:one ${{ matrix.scenario }}
        continue-on-error: ${{ matrix.allow-failure }}
